import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:http/http.dart' as http;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

import '../../../../core/constants/brand_colors.dart';
import '../models/project_model.dart';

class ProjectPreviewScreen extends StatefulWidget {
  final ProjectModel project;

  const ProjectPreviewScreen({super.key, required this.project});

  @override
  State<ProjectPreviewScreen> createState() => _ProjectPreviewScreenState();
}

class _ProjectPreviewScreenState extends State<ProjectPreviewScreen> {
  late String _beforeImage;
  late String _afterImage;
  double _sliderValue = 0.5;

  @override
  void initState() {
    super.initState();

    // Debug: Print project data
    print("🔍 PROJECT DEBUG:");
    print("Project Name: ${widget.project.name}");
    print("Photo Paths Count: ${widget.project.photoPaths.length}");
    print("AI Preview URL: ${widget.project.aiPreviewUrl}");
    print("Carpet Area: ${widget.project.propertyDetails.carpetArea}");
    print("Budget: ${widget.project.technicalRequirements.budget.totalBudget}");
    print("Style: ${widget.project.designPreferences.primaryStyle}");

    // Use the first project photo as 'Before' (USER's uploaded photo)
    if (widget.project.photoPaths.isNotEmpty) {
      _beforeImage = widget.project.photoPaths.first;
      print("✅ BEFORE IMAGE (User Upload): $_beforeImage");
    } else {
      _beforeImage = "";
      print("⚠️ NO BEFORE IMAGE - User didn't upload photos");
    }

    // Use AI-generated preview from backend as 'After'
    _afterImage =
        widget.project.aiPreviewUrl ??
        "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80";

    print("✅ AFTER IMAGE (AI Generated): $_afterImage");

    if (widget.project.aiPreviewUrl == null) {
      print("⚠️ WARNING: AI Preview URL is NULL - using fallback placeholder");
    }
  }

  Future<void> _sharePreview() async {
    try {
      final text =
          '''
AI Interior Design Preview - ${widget.project.name}

Style: ${widget.project.designPreferences.primaryStyle.isEmpty ? "Modern" : widget.project.designPreferences.primaryStyle}
Area: ${widget.project.propertyDetails.carpetArea.toInt()} ${widget.project.propertyDetails.areaUnit}
Budget: ₹${(widget.project.technicalRequirements.budget.totalBudget / 100000).toStringAsFixed(1)}L

Generated by Elite Decora - AI Interior Design Automation
      ''';

      await Share.share(text);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text("Error sharing: $e")));
      }
    }
  }

  Future<void> _generatePDFQuotation() async {
    // Navigate to PDF preview screen
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => _PDFPreviewScreen(
          project: widget.project,
          beforeImage: _beforeImage,
          afterImage: _afterImage,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        title: Text(
          "AI Preview",
          style: TextStyle(color: theme.textTheme.titleLarge?.color),
        ),
        backgroundColor: theme.scaffoldBackgroundColor,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.close, color: theme.iconTheme.color),
          onPressed: () => context.go('/dashboard'),
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.share, color: theme.iconTheme.color),
            onPressed: _sharePreview,
          ),
          IconButton(
            icon: Icon(Icons.picture_as_pdf, color: theme.iconTheme.color),
            onPressed: _generatePDFQuotation,
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // BEFORE/AFTER SLIDER SECTION
            SizedBox(
              height: 400,
              child: Stack(
                children: [
                  // AFTER IMAGE (Background)
                  Positioned.fill(
                    child: Image.network(
                      _afterImage,
                      fit: BoxFit.cover,
                      loadingBuilder: (c, child, p) => p == null
                          ? child
                          : const Center(child: CircularProgressIndicator()),
                      errorBuilder: (c, o, s) => Container(
                        color: Colors.grey[300],
                        child: const Icon(Icons.broken_image),
                      ),
                    ),
                  ),

                  // BEFORE IMAGE (Foreground - Clipped)
                  if (_beforeImage.isNotEmpty)
                    Positioned.fill(
                      child: ClipRect(
                        clipper: _SliderClipper(_sliderValue),
                        child: _buildBeforeImage(),
                      ),
                    ),

                  // SLIDER HANDLE
                  Positioned.fill(
                    child: LayoutBuilder(
                      builder: (context, constraints) {
                        return GestureDetector(
                          onHorizontalDragUpdate: (details) {
                            setState(() {
                              _sliderValue =
                                  (details.localPosition.dx /
                                          constraints.maxWidth)
                                      .clamp(0.0, 1.0);
                            });
                          },
                          child: Stack(
                            children: [
                              Positioned(
                                left: constraints.maxWidth * _sliderValue - 1.5,
                                top: 0,
                                bottom: 0,
                                child: Container(width: 3, color: Colors.white),
                              ),
                              Positioned(
                                left: constraints.maxWidth * _sliderValue - 15,
                                top: constraints.maxHeight / 2 - 15,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: const BoxDecoration(
                                    color: Colors.white,
                                    shape: BoxShape.circle,
                                    boxShadow: [
                                      BoxShadow(
                                        color: Colors.black26,
                                        blurRadius: 4,
                                      ),
                                    ],
                                  ),
                                  child: const Icon(
                                    Icons.compare_arrows,
                                    size: 18,
                                    color: BrandColors.primary,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        );
                      },
                    ),
                  ),

                  // LABELS
                  Positioned(
                    bottom: 20,
                    left: 20,
                    child: _buildLabel("Before"),
                  ),
                  Positioned(
                    bottom: 20,
                    right: 20,
                    child: _buildLabel("After"),
                  ),
                ],
              ),
            ),

            // DETAILS SECTION
            Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    widget.project.designPreferences.primaryStyle.isNotEmpty
                        ? widget.project.designPreferences.primaryStyle
                        : "Modern",
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.bold,
                      color: isDark ? Colors.white : Colors.black,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    "Here is a preview of your new ${widget.project.propertyDetails.spaceTypes.firstOrNull ?? "Room"}. We've applied your selected style and materials.",
                    style: TextStyle(
                      color: isDark ? Colors.grey[400] : Colors.grey[600],
                    ),
                  ),

                  const SizedBox(height: 24),
                  Wrap(
                    spacing: 10,
                    runSpacing: 10,
                    children: [
                      _buildInfoChip(
                        Icons.palette,
                        widget.project.designPreferences.primaryStyle.isEmpty
                            ? "Style"
                            : widget.project.designPreferences.primaryStyle,
                        isDark,
                      ),
                      _buildInfoChip(
                        Icons.square_foot,
                        "${widget.project.propertyDetails.carpetArea.toInt()} ${widget.project.propertyDetails.areaUnit}",
                        isDark,
                      ),
                      _buildInfoChip(
                        Icons.attach_money,
                        "Budget: ₹${(widget.project.technicalRequirements.budget.totalBudget / 100000).toStringAsFixed(1)}L",
                        isDark,
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
        color: Colors.black54,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        text,
        style: const TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.bold,
          fontSize: 12,
        ),
      ),
    );
  }

  Widget _buildInfoChip(IconData icon, String label, bool isDark) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: isDark ? Colors.grey[800] : Colors.grey[100],
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 16, color: BrandColors.primary),
          const SizedBox(width: 8),
          Text(
            label,
            style: TextStyle(
              color: isDark ? Colors.white70 : Colors.black87,
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBeforeImage() {
    if (_beforeImage.isEmpty) return Container(color: Colors.grey);
    if (_beforeImage.startsWith('http')) {
      return Image.network(_beforeImage, fit: BoxFit.cover);
    }
    return Image.file(File(_beforeImage), fit: BoxFit.cover);
  }
}

class _SliderClipper extends CustomClipper<Rect> {
  final double value;
  _SliderClipper(this.value);

  @override
  Rect getClip(Size size) {
    return Rect.fromLTRB(0, 0, size.width * value, size.height);
  }

  @override
  bool shouldReclip(covariant CustomClipper<Rect> oldClipper) => true;
}

class _PDFPreviewScreen extends StatelessWidget {
  final ProjectModel project;
  final String beforeImage;
  final String afterImage;

  const _PDFPreviewScreen({
    required this.project,
    required this.beforeImage,
    required this.afterImage,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Quotation Preview')),
      body: PdfPreview(build: (format) => _generatePdf(format)),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();

    final beforeImageBytes = await _getImageBytes(beforeImage);
    final afterImageBytes = await _getImageBytes(afterImage);

    // Load fonts that support Rupee symbol
    final font = await PdfGoogleFonts.notoSansRegular();
    final fontBold = await PdfGoogleFonts.notoSansBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        theme: pw.ThemeData.withFont(base: font, bold: fontBold),
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          // Header with Logo
          pw.Container(
            alignment: pw.Alignment.center,
            margin: const pw.EdgeInsets.only(bottom: 20),
            child: pw.Column(
              children: [
                pw.Text(
                  'ELITE DECORA',
                  style: pw.TextStyle(
                    fontSize: 32,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'CREATIVE INTERIOR DESIGN',
                  style: pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey600,
                    letterSpacing: 2,
                  ),
                ),
                pw.SizedBox(height: 16),
                pw.Container(
                  height: 2,
                  width: 200,
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Title
          pw.Text(
            'AI INTERIOR DESIGN QUOTATION',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey800,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                _buildPDFInfoRow('Project Name:', project.name),
                pw.SizedBox(height: 8),
                _buildPDFInfoRow(
                  'Design Style:',
                  project.designPreferences.primaryStyle.isEmpty
                      ? "Modern"
                      : project.designPreferences.primaryStyle,
                ),
                pw.SizedBox(height: 8),
                _buildPDFInfoRow(
                  'Property Type:',
                  project.propertyDetails.type.name.toUpperCase(),
                ),
                pw.SizedBox(height: 8),
                _buildPDFInfoRow(
                  'Carpet Area:',
                  '${project.propertyDetails.carpetArea.toInt()} ${project.propertyDetails.areaUnit}',
                ),
                pw.SizedBox(height: 8),
                _buildPDFInfoRow(
                  'Budget:',
                  '₹${(project.technicalRequirements.budget.totalBudget / 100000).toStringAsFixed(1)}L',
                ),
                pw.SizedBox(height: 8),
                _buildPDFInfoRow(
                  'Date:',
                  DateTime.now().toString().split(' ')[0],
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Budget Breakdown
          pw.Text(
            'BUDGET BREAKDOWN',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey800,
            ),
          ),

          pw.SizedBox(height: 12),

          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Column(children: _buildBudgetBreakdown()),
          ),

          pw.SizedBox(height: 24),

          // Before/After Comparison
          pw.Text(
            'DESIGN TRANSFORMATION',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey800,
            ),
          ),

          pw.SizedBox(height: 12),

          // Images side by side
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Before Image
              pw.Expanded(
                child: pw.Column(
                  children: [
                    pw.Container(
                      padding: const pw.EdgeInsets.all(4),
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(
                          color: PdfColors.grey300,
                          width: 2,
                        ),
                      ),
                      child: beforeImageBytes != null
                          ? pw.Image(
                              pw.MemoryImage(beforeImageBytes),
                              height: 200,
                              fit: pw.BoxFit.cover,
                            )
                          : pw.Container(
                              height: 200,
                              color: PdfColors.grey200,
                              child: pw.Center(child: pw.Text('No Image')),
                            ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Container(
                      padding: const pw.EdgeInsets.all(8),
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey800,
                        borderRadius: const pw.BorderRadius.all(
                          pw.Radius.circular(4),
                        ),
                      ),
                      child: pw.Text(
                        'BEFORE',
                        style: const pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 12,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              pw.SizedBox(width: 16),

              // After Image
              pw.Expanded(
                child: pw.Column(
                  children: [
                    pw.Container(
                      padding: const pw.EdgeInsets.all(4),
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(
                          color: PdfColors.grey300,
                          width: 2,
                        ),
                      ),
                      child: afterImageBytes != null
                          ? pw.Image(
                              pw.MemoryImage(afterImageBytes),
                              height: 200,
                              fit: pw.BoxFit.cover,
                            )
                          : pw.Container(
                              height: 200,
                              color: PdfColors.grey200,
                              child: pw.Center(child: pw.Text('No Image')),
                            ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Container(
                      padding: const pw.EdgeInsets.all(8),
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey800,
                        borderRadius: const pw.BorderRadius.all(
                          pw.Radius.circular(4),
                        ),
                      ),
                      child: pw.Text(
                        'AFTER (AI GENERATED)',
                        style: const pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 12,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),

          pw.SizedBox(height: 24),

          // Footer
          pw.Divider(color: PdfColors.grey300),
          pw.SizedBox(height: 12),
          pw.Center(
            child: pw.Column(
              children: [
                pw.Text(
                  'Generated by Elite Decora AI',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Powered by Elite Decora Engine',
                  style: pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey500,
                    fontStyle: pw.FontStyle.italic,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildPDFInfoRow(String label, String value) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey700,
          ),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 11, color: PdfColors.grey900),
        ),
      ],
    );
  }

  List<pw.Widget> _buildBudgetBreakdown() {
    final totalBudget = project.technicalRequirements.budget.totalBudget;

    // Calculate itemized breakdown (percentages based on typical interior design projects)
    final materials = totalBudget * 0.35; // 35% for materials
    final labor = totalBudget * 0.25; // 25% for labor
    final furniture = totalBudget * 0.20; // 20% for furniture
    final lighting = totalBudget * 0.10; // 10% for lighting & electrical
    final design = totalBudget * 0.10; // 10% for design services

    final items = [
      {'name': 'Materials & Finishes', 'amount': materials},
      {'name': 'Labor & Installation', 'amount': labor},
      {'name': 'Furniture & Fixtures', 'amount': furniture},
      {'name': 'Lighting & Electrical', 'amount': lighting},
      {'name': 'Design Services', 'amount': design},
    ];

    final widgets = <pw.Widget>[];

    for (var item in items) {
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                item['name'] as String,
                style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
              ),
              pw.Text(
                '₹${((item['amount'] as double) / 1000).toStringAsFixed(0)}k',
                style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey900,
                ),
              ),
            ],
          ),
        ),
      );
    }

    // Add divider and total
    widgets.add(pw.Divider(color: PdfColors.grey400));
    widgets.add(
      pw.Padding(
        padding: const pw.EdgeInsets.only(top: 8),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'TOTAL BUDGET',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
            pw.Text(
              '₹${(totalBudget / 100000).toStringAsFixed(1)}L',
              style: pw.TextStyle(
                fontSize: 13,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey900,
              ),
            ),
          ],
        ),
      ),
    );

    return widgets;
  }

  Future<Uint8List?> _getImageBytes(String imageUrl) async {
    try {
      if (imageUrl.startsWith('http')) {
        // Network image
        final response = await http.get(Uri.parse(imageUrl));
        if (response.statusCode == 200) {
          return response.bodyBytes;
        }
      } else {
        // Local file
        final file = File(imageUrl);
        if (await file.exists()) {
          return await file.readAsBytes();
        }
      }
    } catch (e) {
      print("Error loading image: $e");
    }
    return null;
  }
}
